### ISSUE TITLE
App to testing portals

### ISSUE THREAD

**Issue by kacperpaczos** [linuxmint/xdg-desktop-portal-xapp#11]
I found this app: https://flathub.org/pl/apps/xyz.tytanium.DoorKnocker
And for now, LM dosen't support these portals:
![image](https://github.com/linuxmint/xdg-desktop-portal-xapp/assets/23406555/ae1fa28c-ee3b-4c5d-b215-37e0ac402460)

**Comment by mtwebster** [comment]
There's a PR open for the Background portal (#13), with #2 being the existing issue for it.

There are quite a few additional portals in Mint 22/Ubuntu 24.04, but we don't plan on implementing anything more for the next release at this time.
