### ISSUE TITLE
Add/Delegate org.freedesktop.impl.portal.Secret 

### ISSUE THREAD

**Issue by 1fexd** [linuxmint/xdg-desktop-portal-xapp#19]
Apps like [PikaBackup](https://gitlab.gnome.org/World/pika-backup) can store backup encryption passwords in the system keyring which is useful for automated backups, but this portal doesn't currently implement `org.freedesktop.impl.portal.Secret`, so PikaBackup always prompts for the password. 

This behavior can also be observed/tested in [ASHPD Demo](https://flathub.org/apps/com.belmoussaoui.ashpd.demo) (scroll to "Secret", then try to "Request" one)

Not sure if it's necessary to actually implement support for this (or just "delegate" (?) it in `/usr/share/xdg-desktop-portal/x-cinnamon-portals.conf`), I found this [PikaBackup issue](https://gitlab.gnome.org/World/pika-backup/-/issues/458#note_1979134) and managed to also get it to work by creating the following file:

`~/.config/xdg-desktop-portal/portals.conf`:

```
[preferred]
default=xapp;gtk;
org.freedesktop.impl.portal.Secret=gnome-keyring;
```

After restarting the service (`systemctl --user restart xdg-desktop-portal`), both ASHPD and PikaBackup can now read from the Gnome keyring.

**Comment by mtwebster** [comment]
Interesting, I didn't know gnome-keyring provided a portal implementation, this should be simple enough then.

**Comment by mtwebster** [comment]
Thanks for your help and doing the research here!
