### ISSUE TITLE
xdg-desktop-portal-xapp sometimes causes gnome-terminal and other gnome apps to hang on start

### ISSUE THREAD

**Issue by li20034** [linuxmint/xdg-desktop-portal-xapp#20]
Hi,

First of all, I would like to say that I really enjoyed using Linux Mint for the past few years. I upgraded from 21.3 to 22 on 2 of my systems, and noticed that sometimes, when logging out and then back in, `gnome-terminal` would take a really long time to start (if it starts at all).

After it starts the first time, subsequent starts are fast. Also, when logging in after a fresh boot, it always works.

When this hang occurs, doing `systemctl --user start xdg-desktop-portal-xapp` and trying to launch gnome-terminal again will always work fine.

When the failure occurs, I see this in the service status (this is from a live cd boot, which also suffers this issue, so it's not related to my configuration or upgrading from 21.3):
```
× xdg-desktop-portal-xapp.service - Portal service (XApp implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-xapp.service; static)
     Active: failed (Result: exit-code) since Wed 2024-07-31 17:32:43 UTC; 1min 6s ago
   Duration: 26.240s
    Process: 2718 ExecStart=/usr/libexec/xdg-desktop-portal-xapp (code=exited, status=1/FAILURE)
   Main PID: 2718 (code=exited, status=1/FAILURE)
        CPU: 15ms

Jul 31 17:32:43 mint systemd[1668]: Starting xdg-desktop-portal-xapp.service - Portal service (XApp implementation)...
Jul 31 17:32:43 mint xdg-desktop-portal-xapp[2718]: Invalid MIT-MAGIC-COOKIE-1 key
Jul 31 17:32:43 mint xdg-desktop-por[2718]: cannot open display: :0
Jul 31 17:32:43 mint systemd[1668]: xdg-desktop-portal-xapp.service: Main process exited, code=exited, status=1/FAILURE
Jul 31 17:32:43 mint systemd[1668]: xdg-desktop-portal-xapp.serviace: Failed with result 'exit-code'.
Jul 31 17:32:43 mint systemd[1668]: Failed to start xdg-desktop-portal-xapp.service - Portal service (XApp implementation).
```

Steps to reproduce:
1. Log in normally after a fresh boot
2. Start gnome terminal (it should work)
3. Log out
4. Wait about 10-15 seconds
5. Log back in
6. Immediately try to start gnome terminal. It won't start, or takes really long to start (if it does start right away, go back to step 3. After 2 tries, this issue always comes up at least once)
7. Now, execute `systemctl --user start xdg-desktop-portal-xapp` (in another terminal, maybe alacritty). A gnome terminal window may pop up right away. If not, relaunching gnome terminal always works correctly at this point.

Any ideas why this happens? Also, this did not happen in Mint 21.3.

**Comment by mtwebster** [comment]
This is being worked on - it's caused by a problem with the new 'Background' portal that manifests when apps and background processes start shutting down during logout.

ref: https://github.com/linuxmint/cinnamon/issues/12321

**Comment by fattila02** [comment]
Add this command to Startup Applications's custom command and problem's solved. For me it's working perfectly.
