### ISSUE TITLE
xdg-desktop-portal-xapp with other desktops than cinnamon cause 30 s delay to launch app.

### ISSUE THREAD

**Issue by Crystal4276** [linuxmint/xdg-desktop-portal-xapp#5]
Hello,
Apps can be launched in cinnamon immediately, but in Qtile it takes about 30s.
So far i have identified GTK apps: gnome-terminal, celluloid, nemo.
The issue appeared after the last update on Arch of some cinnamon packages.
On my system i have installed:
xdg-desktop-portal 1.16.0-3
xdg-desktop-portal-gtk 1.14.1-1
xdg-desktop-portal-xapp 1.0.1-1

In systemd journal:
Jun 09 08:26:58 terrier systemd[952]: Failed to start Portal service (XApp implementation).
Jun 09 08:27:23 terrier xdg-desktop-por[11118]: Failed to create settings proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.xapp: Timeout was reached

**Comment by mtwebster** [comment]
Hi, which other desktops does this occur on?

edit: sorry, I missed qtile, I'll try it out.

**Comment by leigh123linux** [comment]
Seems like portal causes a delay.

https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/74

**Comment by mtwebster** [comment]
Can't reproduce on i3, lxde or Cinnamon (with modified xdg-desktop-portal-xapp that doesn't support it)

I can't get qtile to work yet, and there website is broken.

@leigh123linux I don't think gnome's issue is related - it looks like it was hanging waiting on mutter, we're not doing anything like that.

**Comment by Crystal4276** [comment]
Edit: After the initial start of any GTK app (with the system hanging 30s), then starting times are back to normal.

**Comment by krankenwaerter** [comment]
Same behaviour  on Hyprland WM: GTK apps launch awfully slow, while QT apps open instantly.
Downgrading Cinnamon and uninstalling xdg-desktop-portal-xapp resolved the issue as a temporary workaround.

As a side note: Hyprland ships it's own desktop portal, which is known to conflict with the portals from Gnome and KDE -- this is one of the reasons why I chose Cinnamon as my secondary DE.
https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/

**Comment by rcalixte** [comment]
Someone uploaded a [YouTube video](https://youtu.be/uVWzsDDgUDM?t=391) (starting at the relevant mark) demonstrating the issue with decent detail. Assuming it is as easy to reproduce, hopefully this helps with the root cause.



Side bar: This also highlights that the new adjustable menu could have been communicated better. (Moved to linuxmint/discussions#39)

**Comment by mtwebster** [comment]
The youtube video is no more useful than the descriptions here.

I can't reproduce it on Cinnamon in Mint or Manjaro, I'm thinking there must be some additional factor at play here. The other wms mentioned above aren't useful because [they're broken | under-configured out-of-the-box | I'm stupid].

I've got a fair idea what *might* be causing it but I like to be able to demonstrate to myself that I've fixed something before inflicting it on others.

Do people experiencing this have other desktops' portal packages installed?  When the issue is occurring, which portal processes are running?
```shell
ps -A | grep xdg-desktop
# or (ps -A can cut off long names)
ps auxf | grep xdg-desktop
```

**Comment by mtwebster** [comment]
I did a PR for a change that may help with issues *on other desktops*, but this won't anyone experiencing this in Cinnamon.

You can get a patch for it here:
https://patch-diff.githubusercontent.com/raw/linuxmint/xdg-desktop-portal-xapp/pull/7.patch to stick in your build spec in arch, or wherever.

**Comment by Crystal4276** [comment]
> ```shell
> ps auxf | grep xdg-desktop
> ```

This is what i see on my Arch installation:
```
❯ ps -A | grep xdg-desktop
   4753 ?        00:00:00 xdg-desktop-por
   4768 ?        00:00:00 xdg-desktop-por

~ 
❯ ps auxf | grep xdg-desktop
crystal     4753  0.0  0.0 621780  3612 ?        Ssl  06:33   0:00  \_ /usr/lib/xdg-desktop-portal
crystal     4768  0.0  0.0 449864  4608 ?        Ssl  06:33   0:00  \_ /usr/lib/xdg-desktop-portal-gtk
crystal    85373  0.0  0.0   6580  2280 pts/1    S+   19:50   0:00          \_ grep xdg-desktop
```

**Comment by nick-ulle** [comment]
I think I'm also being affected by this issue. On my machine (Arch), Firefox has similar startup delay after a system update (that updated xdg-desktop-portal-xapp, among other things). I found this error message in the journal:
```
Jun 12 10:32:35 zen xdg-desktop-por[2837]: Theme parsing error: gtk-contained.css:2871:228: Missing closing bracket for :not()
Jun 12 10:32:35 zen systemd[1117]: xdg-desktop-portal-xapp.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ An ExecStart= process belonging to unit UNIT has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Jun 12 10:32:35 zen systemd[1117]: xdg-desktop-portal-xapp.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ The unit UNIT has entered the 'failed' state with result 'exit-code'.
Jun 12 10:32:35 zen systemd[1117]: Failed to start Portal service (XApp implementation).
░░ Subject: A start job for unit UNIT has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit UNIT has finished with a failure.
░░
░░ The job identifier is 355 and the job result is failed.
```

**Comment by mtwebster** [comment]
My patch I referenced should eliminate that exit failure - it was exiting if the desktop wasn't mate, xfce or cinnamon. It should stay running instead.

@nick-ulle what desktop are you using?

**Comment by nick-ulle** [comment]
I'm using bspwm with various Cinnamon services running around it. As soon as I have time, I'll give the patch a try, see if it fixes things, and report back.

**Comment by krankenwaerter** [comment]
> My patch I referenced should eliminate that exit failure - it was exiting if the desktop wasn't mate, xfce or cinnamon. It should stay running instead.

I can confirm that the patch from @mtwebster resolved the issue for me, startup times of the affected GTK apps is back to normal. Good work, thank you for the quick help!

For completeness:
I am running Hyprland alongside Cinnamon on Endeavour OS. Before applying the patch, `ps` showed only xdg-desktop-portal-hyprland running.

```
> systemctl --user status xdg-desktop-portal-xapp                                         
× xdg-desktop-portal-xapp.service - Portal service (XApp implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-xapp.service; static)
     Active: failed (Result: exit-code) since Tue 2023-06-13 15:24:42 CEST; 6min ago
    Process: 1922 ExecStart=/usr/lib/xdg-desktop-portal-xapp (code=exited, status=1/FAILURE)
   Main PID: 1922 (code=exited, status=1/FAILURE)
        CPU: 82ms
```
After installing the patched version of xdg-desktop-portal-xapp everything seems fine.
```
> ps auxf | grep xdg-desktop                                
joerg        783  0.0  0.0 612444 18504 ?        Ssl  18:50   0:00  \_ /usr/lib/xdg-desktop-portal
joerg        845  0.0  0.1 451924 28744 ?        Ssl  18:50   0:00  \_ /usr/lib/xdg-desktop-portal-xapp
joerg        864  0.0  0.2 511240 50668 ?        Ssl  18:50   0:00  \_ /usr/lib/xdg-desktop-portal-hyprland
joerg       1918  0.0  0.0   6940  2796 pts/1    S+   18:51   0:00      \_ grep --color=auto xdg-desktop
```
