### ISSUE TITLE
xviewer: Starts in light mode then changes to dark

### ISSUE THREAD

**Issue by axel358** [linuxmint/xdg-desktop-portal-xapp#8]
This might not be exclusive to xviewer, on Arch it can take up to 5 seconds. Could this be related to the xapp portal? Libhandy and libadwaita apps are taking a very very long time to start under the Cinnamon session, killing the xapps portal fixes it

**Comment by mtwebster** [comment]
How long is very very long?

Do you have the gnome portal installed (xdg-desktop-portal-gnome)?

See:
https://github.com/linuxmint/mint21.2-beta/issues/40

**Comment by axel358** [comment]
With the gnome portal installed it takes up to 25 seconds, removing it fixes long startup time issue, but even without it I still can see xviewer being light then change to dark after 2 or 3 seconds the first time u open it on a fresh boot

**Comment by hugok79** [comment]
In Manjaro to fix this slow start in Firefox, LibreOffice apps:
Remove **xdg-desktop-portal-gnome** and install **xdg-desktop-portal-gtk** fix the issue
